import { contactMailto, navItems, siteConfig } from "@/lib/site"

const resourceLinks = [
  { label: "Main website", href: siteConfig.mainSiteUrl, external: true },
  { label: "Mailing list", href: siteConfig.mailingListUrl, external: true },
  { label: "Apply", href: siteConfig.applicationFormUrl, external: true },
  { label: "Contact", href: contactMailto, external: false },
  // Review aid: the pre-redesign build, generated by `bun run build:legacy`.
  // Remove this entry when the comparison is no longer needed.
  { label: "Previous design", href: "/old/", external: false },
]

export function SiteFooter() {
  return (
    <footer className="overflow-hidden border-t border-border">
      <div className="container pt-20 pb-10">
        <div className="grid gap-12 sm:grid-cols-2 lg:grid-cols-[1fr_auto_auto] lg:gap-24">
          <div className="max-w-sm">
            <p className="label-micro text-muted-foreground">
              MRG &times; UTAR
            </p>
            <p className="mt-5 leading-relaxed text-muted-foreground">
              A research competition basecamp for students across Malaysia and
              the wider ASEAN region.
            </p>
          </div>

          <nav>
            <h2 className="label-micro text-muted-foreground">Sections</h2>
            <ul className="mt-5 space-y-3">
              {navItems.map((item) => (
                <li key={item.href}>
                  <a href={item.href} className="link-wipe text-sm">
                    {item.label}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          <nav>
            <h2 className="label-micro text-muted-foreground">Elsewhere</h2>
            <ul className="mt-5 space-y-3">
              {resourceLinks.map((link) => (
                <li key={link.label}>
                  <a
                    href={link.href}
                    target={link.external ? "_blank" : undefined}
                    rel={link.external ? "noopener noreferrer" : undefined}
                    className="link-wipe text-sm"
                  >
                    {link.label}
                  </a>
                </li>
              ))}
            </ul>
          </nav>
        </div>

        <p className="label-micro mt-20 text-muted-foreground">
          &copy; 2026 MYResearchGuide &middot; Research Competition Basecamp
        </p>
      </div>

      {/* Oversized wordmark. Drawn as SVG with textLength so it always spans
          the container exactly, at any viewport width, without overflowing. */}
      <div aria-hidden className="container pb-6">
        <svg
          viewBox="0 0 1200 212"
          className="w-full select-none"
          preserveAspectRatio="xMidYMid meet"
          role="presentation"
        >
          <text
            x="0"
            y="158"
            textLength="1200"
            lengthAdjust="spacingAndGlyphs"
            fill="currentColor"
            style={{
              fontFamily: "var(--font-display)",
              fontSize: "200px",
              letterSpacing: "-0.03em",
            }}
          >
            MYResearchGuide
          </text>
        </svg>
      </div>
    </footer>
  )
}
